fullnameOverride: "highflame-dlp"
progressDeadlineSeconds: 1200

livenessProbe:
  httpGet:
    path: /v1/guard/local_dlp/healthz
    port: 8888
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

readinessProbe:
  httpGet:
    path: /v1/guard/local_dlp/healthz
    port: 8888
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

nodeSelector:
  kube/nodegroup: "general"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 1

service:
  type: ClusterIP
  protocol: TCP
  port: 8888

image:
  repository: "${DOCKER_IMAGE}"
  pullPolicy: Always
  tag: ${IMAGE_TAG}

imagePullSecrets:
  - name: javelin-registry-secret

resources:
  requests:
    memory: 1536Mi
    cpu: 300m
  limits:
    memory: 2048Mi
    cpu: 1000m