extraScrapeConfigs: |
  - job_name: 'highflame-metrics'
    metrics_path: '/v1/metrics/usage'
    static_configs:
      - targets:
          - highflame-core.${service_namespace}.svc.cluster.local:8000
  - job_name: 'highflame-system-metrics'
    metrics_path: 'v1/metrics/system'
    static_configs:
      - targets:
        - highflame-core.${service_namespace}.svc.cluster.local:8000

server:
  # # prefixURL: /
  # # baseURL: https://prometheus_url/prometheus
  # extraFlags:
  #   - web.enable-lifecycle
  #   - web.route-prefix=/
  #   - web.external-url=https://prometheus_url/prometheus
  retention: "365d"
  retentionSize: "512GB"
  persistentVolume:
    enabled: true
    size: ${prometheus_disk_size}
    storageClass: ${storage_classname}

  # service:
  #   annotations:
  #     alb.ingress.kubernetes.io/healthcheck-path: /graph
  #   type: NodePort
  #   protocol: TCP
  #   port: 80

  service:
    type: ClusterIP
    protocol: TCP
    port: 80

alertmanager:
  enabled: true
  persistence:
    enabled: true
    storageClass: ${storage_classname}
    size: 2Gi

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: false