fullnameOverride: "highflame-admin"

livenessProbe:
  httpGet:
    path: /v1/admin/healthz
    port: 8040
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

readinessProbe:
  httpGet:
    path: /v1/admin/healthz
    port: 8040
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

nodeSelector:
  kube/nodegroup: "general"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  type: NodePort
  protocol: TCP
  port: 8040

image:
  repository: "${DOCKER_IMAGE}"
  pullPolicy: Always
  tag: ${IMAGE_TAG}

imagePullSecrets:
  - name: highflame-registry-secret

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 1024Mi
    cpu: 500m

secrets:
  enabled: true
  secretData:
    # Please refer https://github.com/highflame-ai/highflame-iac/blob/main/docs/service-vars.md

volumes:
  - name: license-volume
    secret:
      secretName: highflame-license
      optional: false
  - name: jwt-keys
    secret:
      secretName: highflame-jwt-keys
      optional: false
  # - name: redis-cert-volume
  #   secret:
  #     secretName: highflame-redis-cert
  #     optional: false

volumeMounts:
  - name: license-volume
    mountPath: "/app/license"
    readOnly: true
  - name: jwt-keys
    mountPath: "/app/config/jwt"
    readOnly: true
  # - name: redis-cert-volume
  #   mountPath: "/app/certs/redis-ca.pem"
  #   readOnly: true
  #   subPath: redis-ca.pem

serviceAccount:
  create: true
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: "${SVC_IAM_ROLE}"
  rules:
    - apiGroups: [ "" ]
      resources: [ "secrets" ]
      verbs: [ "get", "list", "create", "update", "patch", "delete" ]

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /v1/admin/healthz
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/group.order: '2'
    alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=300"

    alb.ingress.kubernetes.io/load-balancer-name: ${K8S_CLUSTER_NAME}-alb-ingress
    alb.ingress.kubernetes.io/group.name: ${K8S_CLUSTER_NAME}-group
    alb.ingress.kubernetes.io/subnets: ${PUBLIC_SUBNET_IDS}
    alb.ingress.kubernetes.io/certificate-arn: ${ACM_CERTIFICATE_ARN}
    alb.ingress.kubernetes.io/security-groups: ${ALB_SECURITY_GROUP_IDS}
  hosts:
    - host: api-dev.example.com
      paths:
        - path: /v1/admin/
          pathType: Prefix
        - path: /v2/admin/
          pathType: Prefix